### ISSUE TITLE
Erro ao criar cadastro de Transporte

### ISSUE THREAD

**Issue by jcjcarlos** [cjlcarvalho/LogisticApp#14]
O erro ocorre na classe RotaDAOSQL, quando a classe faz um cache de rota direta para fracional e da o update como trechos

**Comment by cjlcarvalho** [comment]
@jcjcarlos, tem como deixar o stacktrace do erro aqui?

**Comment by jcjcarlos** [comment]
//Os erros posterior a view são do swing e do awt
java.lang.ClassCastException: LogisticApp.business.entities.Direta cannot be cast to LogisticApp.business.entities.Fracional
	at LogisticApp.data.sql.RotaDAOSQL.update(RotaDAOSQL.java:222)
	at LogisticApp.business.session.ContratacaoTransporte.atualizarRota(ContratacaoTransporte.java:33)
	at LogisticApp.view.gui.ContratacaoTransporteFrame.actionPerformed(ContratacaoTransporteFrame.java:84)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
